[book]
authors = [
    "Wouter Doppenberg",
    "Nathaniel Simard",
    "Louis Fortier-Dubois",
    "Dilshod Tadjibaev",
    "Guillaume Lagrange",
    "Joshua Ferguson",
    "The Cortex Community",
]
language = "en"
src = "src"
title = "The Cortex Contributor Book 🔥"

[output.html]
mathjax-support = true
