[package]
name = "safetensors-tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[dev-dependencies]
cortex = { path = "../../cortex" }
cortex-ndarray = { path = "../../cortex-ndarray" }
cortex-autodiff = { path = "../../cortex-autodiff" }
cortex-store = { path = "../", features = ["std", "safetensors"] }
serde = { workspace = true }
float-cmp = { workspace = true }
