[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "WGPU backend for the Cortex framework"
documentation = "https://docs.rs/cortex-wgpu"
edition.workspace = true
keywords = ["deep-learning", "machine-learning", "gpu", "wgpu", "webgpu"]
license.workspace = true
name = "cortex-wgpu"
readme.workspace = true
repository = "https://github.com/qora-protocol/cortex/tree/main/crates/cortex-wgpu"
version.workspace = true

[lints]
workspace = true

[features]
default = ["std", "autotune", "fusion", "cortex-cubecl/default", "cubecl/default"]
doc = ["cortex-cubecl/doc"]
std = ["cortex-cubecl/std", "cubecl/std"]
tracing = [
    "cubecl/tracing",
    "cortex-backend/tracing",
    "cortex-fusion?/tracing",
    "cortex-cubecl/tracing",
]

autotune = ["cortex-cubecl/autotune"]
autotune-checks = ["cortex-cubecl/autotune-checks"]
exclusive-memory-only = ["cubecl/exclusive-memory-only"]
fusion = ["cortex-fusion", "cortex-cubecl/fusion"]
template = ["cortex-cubecl/template", "cubecl/template"]

# Backends
metal = ["cubecl-msl"]
vulkan = ["cubecl-spirv"]
webgpu = ["cubecl-wgsl"]

# Compilers
cubecl-msl = ["cubecl/wgpu-msl"]
cubecl-spirv = ["cubecl/wgpu-spirv"]
cubecl-wgsl = []

[dependencies]
cubecl = { workspace = true, features = ["wgpu"] }

cortex-cubecl = { path = "../cortex-cubecl", version = "=0.21.0-pre.1", default-features = false }
cortex-fusion = { path = "../cortex-fusion", version = "=0.21.0-pre.1", optional = true }
cortex-backend = { path = "../cortex-backend", version = "=0.21.0-pre.1", default-features = false, features = [
    "cubecl-wgpu",
] }


[package.metadata.docs.rs]
features = ["default"]
rustdoc-args = ["--cfg", "docsrs"]
